nelmio_cors:
    defaults:
        allow_origin: ['https://s5-5718.nuage-peda.fr']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null
