parameters:
    app_url: 'http://s5-5717.nuage-peda.fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\DataPersister\UserDataPersister:
        tags: [api_platform.data_persister]

    App\State\UserStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
    
    App\Service\EncryptionService:
        arguments:
            $secretKey: 'y3Gv8nM4sT2qX1kP0a9Zc7WdJr5HbEuL'

    App\Serializer\PaymentMethodNormalizer:
        arguments:
            $normalizer: '@api_platform.serializer.normalizer.item'
        tags:
            - { name: 'serializer.normalizer', priority: 20 }

    App\State\PaymentMethodStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\EventListener\PaymentMethodListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    App\EventListener\AddressListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    acme_api.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_authentication_success', method: 'onAuthenticationSuccessResponse' }

    App\DataTransformer\ProductInputDataTransformer:
        tags: ['api_platform.state_processor']

    App\DataTransformer\:
        resource: '../src/DataTransformer'
        tags: ['container.service']
